func test() throws {
	readFileText("testfile");
}

func test2() throws {
	test();
}

func test3() {
	try {
		test2();
	} catch (e) {
		println("Exception value:", "\"" + e + "\"");
	}
}

func main() {
	test3();
}
